name: Deploy website on push

on:
  push:
    branches: [ main ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install SSH Key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy website with rsync
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_WEBSITE_DIR: ${{ secrets.REMOTE_WEBSITE_DIR }}
        SSH_PORT: ${{ secrets.SSH_PORT || '22' }}
      run: |
        set -euo pipefail

        WORKSPACE=${GITHUB_WORKSPACE:-$PWD}
        # If a website/ subdirectory exists in the workspace, use it. Otherwise use the workspace root.
        if [ -d "$WORKSPACE/website" ]; then
          SCRIPT_DIR="$WORKSPACE/website"
        else
          SCRIPT_DIR="$WORKSPACE"
        fi

        echo "Deploying website to $SSH_USER@$SSH_HOST:$REMOTE_WEBSITE_DIR (port $SSH_PORT)"

        echo "Remote listing before sync:"
        ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "ls -la $REMOTE_WEBSITE_DIR || true"

        echo "Syncing website/ (mirror, will delete remote extras)"
        rsync -avz --delete -e "ssh -p $SSH_PORT" "$SCRIPT_DIR/" "$SSH_USER@$SSH_HOST:$REMOTE_WEBSITE_DIR/" || true

        echo "Remote listing after sync:"
        ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "ls -la $REMOTE_WEBSITE_DIR || true"

        echo "Done."
