name: Deploy website on push

on:
  push:
    branches: [ main ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install SSH Key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy website with rsync
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_WEBSITE_DIR: ${{ secrets.REMOTE_WEBSITE_DIR }}
      run: |
        set -euo pipefail

        WORKSPACE=${GITHUB_WORKSPACE:-$PWD}
        SCRIPT_DIR="$WORKSPACE/website"

        echo "Deploying website to $SSH_USER@$SSH_HOST:$REMOTE_WEBSITE_DIR (port 22)"

        echo "Syncing website/"
        rsync -avz -e "ssh -p 22" "$SCRIPT_DIR/" "$SSH_USER@$SSH_HOST:$REMOTE_WEBSITE_DIR/" || true

        echo "Done."
